# Generated by Django 5.1.7 on 2025-03-21 00:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registros',
            new_name='Registro',
        ),
    ]
